# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShopwareCli < Formula
  desc "Shopware CLI helps Shopware developers manage extensions"
  homepage "https://friendsofshopware.com"
  version "0.4.48"
  license "MIT"

  depends_on "git" => :optional
  depends_on "node" => :optional
  depends_on "node-sass"

  on_macos do
    on_intel do
      url "https://github.com/FriendsOfShopware/shopware-cli/releases/download/0.4.48/shopware-cli_Darwin_x86_64.tar.gz"
      sha256 "04730e7df4cd5398614748fb228af48429143201c8fb19cfe2a61087e6042230"

      def install
        bin.install "shopware-cli"
        bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
        zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
        fish_completion.install "completions/shopware-cli.fish"
      end
    end
    on_arm do
      url "https://github.com/FriendsOfShopware/shopware-cli/releases/download/0.4.48/shopware-cli_Darwin_arm64.tar.gz"
      sha256 "482130da2d0da03cc14bd96486c0693d1ff938f54cb2420bf5474e07595b20f8"

      def install
        bin.install "shopware-cli"
        bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
        zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
        fish_completion.install "completions/shopware-cli.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FriendsOfShopware/shopware-cli/releases/download/0.4.48/shopware-cli_Linux_x86_64.tar.gz"
        sha256 "ed47b7c170f1db0a8753e6d67f39e399cc11f22707c8a702021339abd6efd78d"

        def install
          bin.install "shopware-cli"
          bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
          zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
          fish_completion.install "completions/shopware-cli.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FriendsOfShopware/shopware-cli/releases/download/0.4.48/shopware-cli_Linux_arm64.tar.gz"
        sha256 "93aeb0a700fd2ad531ad4c4ab384876c2c72feda5097ddf8cbf3509bd6026a8b"

        def install
          bin.install "shopware-cli"
          bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
          zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
          fish_completion.install "completions/shopware-cli.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/shopware-cli --version"
  end
end
