# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShopwareCli < Formula
  desc "Shopware CLI helps Shopware developers manage extensions"
  homepage "https://friendsofshopware.com"
  version "0.1.67"
  license "MIT"

  depends_on "git" => :optional
  depends_on "node" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FriendsOfShopware/shopware-cli/releases/download/0.1.67/shopware-cli_Darwin_x86_64.tar.gz"
      sha256 "6bc3b3db7521d9de3cc98e6b9637c9ad2031ec23cfe9c991c38e57bbecd9adbb"

      def install
        bin.install "shopware-cli"
        bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
        zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
        fish_completion.install "completions/shopware-cli.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FriendsOfShopware/shopware-cli/releases/download/0.1.67/shopware-cli_Darwin_arm64.tar.gz"
      sha256 "79289adc0bdb9b24c33d2a04649b07477ab9db4a6147439e0ab05c6a907f5a23"

      def install
        bin.install "shopware-cli"
        bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
        zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
        fish_completion.install "completions/shopware-cli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FriendsOfShopware/shopware-cli/releases/download/0.1.67/shopware-cli_Linux_arm64.tar.gz"
      sha256 "303934c757fcf15bf2618118124f9372e1a59f45ef8144a9daf5cc282c6993ff"

      def install
        bin.install "shopware-cli"
        bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
        zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
        fish_completion.install "completions/shopware-cli.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FriendsOfShopware/shopware-cli/releases/download/0.1.67/shopware-cli_Linux_x86_64.tar.gz"
      sha256 "231ace6ce545dd73687dabc6081b7c16e53ad5da7c8ba3d9c91b4691f1bb919f"

      def install
        bin.install "shopware-cli"
        bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
        zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
        fish_completion.install "completions/shopware-cli.fish"
      end
    end
  end

  test do
    system "#{bin}/shopware-cli --version"
  end
end
