# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShopwareCli < Formula
  desc "Shopware CLI helps Shopware developers manage extensions"
  homepage "https://friendsofshopware.com"
  version "0.4.44"
  license "MIT"

  depends_on "git" => :optional
  depends_on "node" => :optional
  depends_on "node-sass"

  on_macos do
    on_intel do
      url "https://github.com/FriendsOfShopware/shopware-cli/releases/download/0.4.44/shopware-cli_Darwin_x86_64.tar.gz"
      sha256 "a0c20a6ae88420895e381c805d845bcf72ee4a1837dc23542944fcdf5ba7b077"

      def install
        bin.install "shopware-cli"
        bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
        zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
        fish_completion.install "completions/shopware-cli.fish"
      end
    end
    on_arm do
      url "https://github.com/FriendsOfShopware/shopware-cli/releases/download/0.4.44/shopware-cli_Darwin_arm64.tar.gz"
      sha256 "64e162ec76e28bfcca9970cfb396f1166d52d4f1bed725dfd94d3f0f35142961"

      def install
        bin.install "shopware-cli"
        bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
        zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
        fish_completion.install "completions/shopware-cli.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FriendsOfShopware/shopware-cli/releases/download/0.4.44/shopware-cli_Linux_x86_64.tar.gz"
        sha256 "a2b1a180764716a49795830981a92ebb08321d6fb69bd242f44cf35bd893d2f6"

        def install
          bin.install "shopware-cli"
          bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
          zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
          fish_completion.install "completions/shopware-cli.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FriendsOfShopware/shopware-cli/releases/download/0.4.44/shopware-cli_Linux_arm64.tar.gz"
        sha256 "2e506f0bedab5de89113a3e88c09d22393a9b900a85e0de5dac834805d835f8d"

        def install
          bin.install "shopware-cli"
          bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
          zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
          fish_completion.install "completions/shopware-cli.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/shopware-cli --version"
  end
end
