# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShopwareCli < Formula
  desc "Shopware CLI helps Shopware developers manage extensions"
  homepage "https://shopware.com"
  version "0.6.13"
  license "MIT"

  depends_on "git" => :optional
  depends_on "node" => :optional
  depends_on "node-sass"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shopware/shopware-cli/releases/download/0.6.13/shopware-cli_Darwin_x86_64.tar.gz"
      sha256 "0b6f63cd15b9d6c97a5eba94979f3f385e9176c9bf8b42fb09b25535a1a1cdf5"

      def install
        bin.install "shopware-cli"
        bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
        zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
        fish_completion.install "completions/shopware-cli.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shopware/shopware-cli/releases/download/0.6.13/shopware-cli_Darwin_arm64.tar.gz"
      sha256 "5764d76a8ca3854b65aa8c5a601b1468815d366d6045191839a5c09848b424eb"

      def install
        bin.install "shopware-cli"
        bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
        zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
        fish_completion.install "completions/shopware-cli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/shopware/shopware-cli/releases/download/0.6.13/shopware-cli_Linux_x86_64.tar.gz"
      sha256 "995fb0d76cd49675332a3cb024c65bb748476397c8492c2584f1993a4e26df9d"
      def install
        bin.install "shopware-cli"
        bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
        zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
        fish_completion.install "completions/shopware-cli.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/shopware/shopware-cli/releases/download/0.6.13/shopware-cli_Linux_arm64.tar.gz"
      sha256 "7891b3d9d15fe11ea95b891c0547d0e107bb3966d4ffb10a1c27f419e821c345"
      def install
        bin.install "shopware-cli"
        bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
        zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
        fish_completion.install "completions/shopware-cli.fish"
      end
    end
  end

  test do
    system "#{bin}/shopware-cli --version"
  end
end
