issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:FriendsOfShopware/shopware-cli:ref:refs/tags/[0-9]+\.[0-9]+\.[0-9]+
claim_pattern:
  job_workflow_ref: FriendsOfShopware/shopware-cli/.github/workflows/release.yml@refs/tags/[0-9]+\.[0-9]+\.[0-9]+

permissions:
  contents: write
